const recipes = [
  {
    title: "Vegetable Stir Fry with Tofu",
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    tags: ["Vegetarian", "Quick", "Healthy"],
    prepTime: "15 min",
    cookTime: "10 min",
    servings: "4",
    nutrition: {
      calories: "320 kcal",
      protein: "18g",
      carbs: "32g",
      fat: "14g",
    },
    ingredients: [
      "14 oz firm tofu, pressed and cubed",
      "2 tbsp vegetable oil",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "2 carrots, julienned",
      "1 cup broccoli florets",
      "2 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "3 tbsp soy sauce",
      "1 tbsp sesame oil",
      "2 green onions, sliced",
    ],
    instructions: [
      "Press tofu to remove excess water, then cut into 1-inch cubes.",
      "Heat vegetable oil in a large wok or skillet over medium-high heat.",
      "Add tofu and cook until golden brown on all sides, about 5 minutes. Remove and set aside.",
      "In the same pan, add garlic and ginger, stir for 30 seconds until fragrant.",
      "Add all vegetables and stir-fry for 4-5 minutes until crisp-tender.",
      "Return tofu to the pan, add soy sauce and sesame oil, toss to combine.",
      "Garnish with sliced green onions and serve hot with rice or noodles.",
    ],
  },
  {
    title: "Mediterranean Quinoa Bowl",
    image:
      "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
    tags: ["Mediterranean", "Healthy", "Meal Prep"],
    prepTime: "20 min",
    cookTime: "15 min",
    servings: "4",
    nutrition: {
      calories: "420 kcal",
      protein: "15g",
      carbs: "52g",
      fat: "18g",
    },
    ingredients: [
      "1 cup quinoa, rinsed",
      "2 cups vegetable broth",
      "1 cucumber, diced",
      "1 cup cherry tomatoes, halved",
      "1/2 red onion, finely diced",
      "1/2 cup kalamata olives, pitted and sliced",
      "1/2 cup feta cheese, crumbled",
      "1/4 cup fresh parsley, chopped",
      "3 tbsp olive oil",
      "2 tbsp lemon juice",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Combine quinoa and vegetable broth in a medium saucepan. Bring to a boil, then reduce heat to low, cover, and simmer for 15 minutes until liquid is absorbed.",
      "Remove from heat and let stand, covered, for 5 minutes. Fluff with a fork and let cool slightly.",
      "In a large bowl, combine cooked quinoa, cucumber, tomatoes, red onion, olives, and feta cheese.",
      "In a small bowl, whisk together olive oil, lemon juice, oregano, salt, and pepper.",
      "Pour dressing over the quinoa mixture and toss to combine.",
      "Sprinkle with fresh parsley before serving. Can be served warm or cold.",
    ],
  },
  {
    title: "Creamy Mushroom Pasta",
    image:
      "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    tags: ["Pasta", "Comfort Food", "Vegetarian"],
    prepTime: "10 min",
    cookTime: "20 min",
    servings: "4",
    nutrition: {
      calories: "520 kcal",
      protein: "14g",
      carbs: "65g",
      fat: "22g",
    },
    ingredients: [
      "12 oz fettuccine pasta",
      "2 tbsp olive oil",
      "1 lb mixed mushrooms (cremini, shiitake, oyster), sliced",
      "3 cloves garlic, minced",
      "1 shallot, finely diced",
      "1 cup heavy cream",
      "1/2 cup vegetable broth",
      "1/2 cup grated Parmesan cheese",
      "2 tbsp fresh thyme leaves",
      "Salt and black pepper to taste",
      "2 tbsp fresh parsley, chopped",
    ],
    instructions: [
      "Cook pasta according to package instructions until al dente. Reserve 1/2 cup pasta water before draining.",
      "While pasta cooks, heat olive oil in a large skillet over medium-high heat.",
      "Add mushrooms and cook without stirring for 3-4 minutes to brown, then stir and continue cooking until golden, about 5 minutes total.",
      "Add garlic and shallot, cook for 1 minute until fragrant.",
      "Pour in heavy cream and vegetable broth, bring to a simmer and cook for 3-4 minutes until slightly thickened.",
      "Stir in Parmesan cheese and thyme until cheese is melted and sauce is smooth.",
      "Add drained pasta to the sauce, tossing to coat. If needed, add reserved pasta water to thin the sauce.",
      "Season with salt and pepper to taste, garnish with fresh parsley before serving.",
    ],
  },
  {
    title: "Spicy Black Bean Tacos",
    image:
      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1080&q=80",
    tags: ["Mexican", "Vegan", "Quick"],
    prepTime: "15 min",
    cookTime: "10 min",
    servings: "4",
    nutrition: {
      calories: "380 kcal",
      protein: "12g",
      carbs: "58g",
      fat: "10g",
    },
    ingredients: [
      "8 corn tortillas",
      "2 cans (15 oz each) black beans, drained and rinsed",
      "1 tbsp olive oil",
      "1 onion, diced",
      "1 red bell pepper, diced",
      "2 cloves garlic, minced",
      "1 tbsp chili powder",
      "1 tsp cumin",
      "1/2 tsp smoked paprika",
      "1/4 tsp cayenne pepper (optional)",
      "1/4 cup vegetable broth",
      "1 avocado, sliced",
      "1 cup shredded lettuce",
      "1/2 cup pico de gallo",
      "Lime wedges for serving",
    ],
    instructions: [
      "Heat olive oil in a large skillet over medium heat. Add onion and bell pepper, cook for 5 minutes until softened.",
      "Add garlic, chili powder, cumin, smoked paprika, and cayenne (if using), cook for 30 seconds until fragrant.",
      "Add black beans and vegetable broth, simmer for 5 minutes, mashing some beans with the back of a spoon.",
      "Warm tortillas according to package instructions or in a dry skillet.",
      "Assemble tacos by filling each tortilla with the black bean mixture, topped with lettuce, avocado slices, and pico de gallo.",
      "Serve with lime wedges on the side.",
    ],
  },
  {
    title: "Lemon Garlic Roasted Chicken",
    image:
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
    tags: ["Protein", "Dinner", "Meal Prep"],
    prepTime: "15 min",
    cookTime: "45 min",
    servings: "4",
    nutrition: {
      calories: "420 kcal",
      protein: "38g",
      carbs: "8g",
      fat: "26g",
    },
    ingredients: [
      "4 chicken breasts, bone-in, skin-on",
      "3 tbsp olive oil",
      "4 cloves garlic, minced",
      "2 lemons (1 zested and juiced, 1 sliced)",
      "2 tbsp fresh rosemary, chopped",
      "1 tbsp fresh thyme leaves",
      "1 tsp salt",
      "1/2 tsp black pepper",
      "1/2 cup chicken broth",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "In a small bowl, mix olive oil, minced garlic, lemon zest, lemon juice, rosemary, thyme, salt, and pepper.",
      "Place chicken breasts in a baking dish, skin side up. Rub the herb mixture all over the chicken, getting some under the skin.",
      "Arrange lemon slices around and under the chicken. Pour chicken broth into the bottom of the dish.",
      "Roast for 35-45 minutes, until chicken reaches an internal temperature of 165°F (74°C) and skin is golden and crispy.",
      "Let rest for 5-10 minutes before serving. Spoon pan juices over chicken when serving.",
    ],
  },
  {
    title: "Berry Smoothie Bowl",
    image:
      "https://images.unsplash.com/photo-1494597564530-871f2b93ac55?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1013&q=80",
    tags: ["Breakfast", "Healthy", "Vegan"],
    prepTime: "10 min",
    cookTime: "0 min",
    servings: "2",
    nutrition: {
      calories: "320 kcal",
      protein: "8g",
      carbs: "62g",
      fat: "6g",
    },
    ingredients: [
      "2 frozen bananas",
      "1 cup frozen mixed berries (strawberries, blueberries, raspberries)",
      "1/2 cup plant-based milk (almond, oat, or coconut)",
      "1 tbsp chia seeds",
      "1 tbsp maple syrup (optional)",
      "Toppings: fresh berries, sliced banana, granola, coconut flakes, hemp seeds",
    ],
    instructions: [
      "Add frozen bananas, mixed berries, plant milk, chia seeds, and maple syrup (if using) to a blender.",
      "Blend until smooth and creamy. The mixture should be thicker than a regular smoothie.",
      "If too thick, add a splash more milk. If too thin, add more frozen fruit.",
      "Pour into bowls and arrange toppings in an attractive pattern.",
      "Serve immediately before it melts.",
    ],
  },
  {
    title: "Chickpea Curry",
    image:
      "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    tags: ["Indian", "Vegan", "One Pot"],
    prepTime: "15 min",
    cookTime: "25 min",
    servings: "4",
    nutrition: {
      calories: "380 kcal",
      protein: "14g",
      carbs: "52g",
      fat: "12g",
    },
    ingredients: [
      "2 cans (15 oz each) chickpeas, drained and rinsed",
      "1 onion, finely chopped",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "1 can (14 oz) diced tomatoes",
      "1 can (14 oz) coconut milk",
      "2 tbsp vegetable oil",
      "2 tbsp curry powder",
      "1 tsp ground cumin",
      "1 tsp ground coriander",
      "1/2 tsp turmeric",
      "1/4 tsp cayenne pepper (adjust to taste)",
      "1 cup spinach, chopped",
      "Salt to taste",
      "Fresh cilantro for garnish",
      "Cooked rice for serving",
    ],
    instructions: [
      "Heat oil in a large pot over medium heat. Add onion and cook until softened, about 5 minutes.",
      "Add garlic and ginger, cook for 1 minute until fragrant.",
      "Stir in curry powder, cumin, coriander, turmeric, and cayenne pepper. Cook for 30 seconds to toast the spices.",
      "Add diced tomatoes and cook for 3-4 minutes, stirring occasionally.",
      "Add chickpeas and coconut milk, bring to a simmer. Reduce heat to low and cook for 15 minutes, stirring occasionally.",
      "Stir in chopped spinach and cook until wilted, about 2 minutes.",
      "Season with salt to taste. Garnish with fresh cilantro and serve over rice.",
    ],
  },
  {
    title: "Avocado Toast with Poached Egg",
    image:
      "https://images.unsplash.com/photo-1525351484163-7529414344d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=880&q=80",
    tags: ["Breakfast", "Quick", "Protein"],
    prepTime: "10 min",
    cookTime: "5 min",
    servings: "2",
    nutrition: {
      calories: "340 kcal",
      protein: "14g",
      carbs: "28g",
      fat: "20g",
    },
    ingredients: [
      "2 slices whole grain bread",
      "1 ripe avocado",
      "2 eggs",
      "1 tbsp white vinegar",
      "1/2 lemon, juiced",
      "Red pepper flakes, to taste",
      "Salt and black pepper, to taste",
      "2 tbsp microgreens or sprouts (optional)",
      "Extra virgin olive oil, for drizzling",
    ],
    instructions: [
      "Toast the bread slices until golden brown.",
      "Cut the avocado in half, remove the pit, and scoop the flesh into a bowl. Add lemon juice, salt, and pepper, then mash with a fork to desired consistency.",
      "For poached eggs: Bring a pot of water to a gentle simmer, add vinegar. Create a whirlpool with a spoon, then carefully crack an egg into the center. Cook for 3 minutes for a runny yolk. Remove with a slotted spoon and place on a paper towel to drain.",
      "Spread the mashed avocado evenly on the toast slices.",
      "Top each toast with a poached egg, sprinkle with red pepper flakes, additional salt and pepper if desired.",
      "Garnish with microgreens and a drizzle of olive oil before serving.",
    ],
  },
  {
    title: "Honey Garlic Salmon",
    image:
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    tags: ["Seafood", "Quick", "High Protein"],
    prepTime: "10 min",
    cookTime: "15 min",
    servings: "4",
    nutrition: {
      calories: "380 kcal",
      protein: "34g",
      carbs: "14g",
      fat: "20g",
    },
    ingredients: [
      "4 salmon fillets (6 oz each)",
      "4 cloves garlic, minced",
      "2 tbsp honey",
      "2 tbsp soy sauce",
      "1 tbsp olive oil",
      "1 tbsp rice vinegar",
      "1 tbsp fresh ginger, grated",
      "1 lemon, sliced",
      "2 tbsp fresh parsley, chopped",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line a baking sheet with parchment paper or foil.",
      "In a small bowl, whisk together garlic, honey, soy sauce, olive oil, rice vinegar, and ginger.",
      "Place salmon fillets on the prepared baking sheet, skin side down. Season with salt and pepper.",
      "Pour the honey garlic mixture over the salmon, making sure it's well coated.",
      "Place lemon slices on top and around the salmon.",
      "Bake for 12-15 minutes, or until salmon flakes easily with a fork.",
      "Garnish with fresh parsley before serving.",
    ],
  },
  {
    title: "Quinoa Stuffed Bell Peppers",
    image:
      "https://images.unsplash.com/photo-1600335895229-6e75511892c8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
    tags: ["Vegetarian", "Meal Prep", "Healthy"],
    prepTime: "20 min",
    cookTime: "40 min",
    servings: "6",
    nutrition: {
      calories: "290 kcal",
      protein: "10g",
      carbs: "42g",
      fat: "9g",
    },
    ingredients: [
      "6 bell peppers (any color), tops cut off and seeds removed",
      "1 cup quinoa, rinsed",
      "2 cups vegetable broth",
      "1 tbsp olive oil",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 zucchini, diced",
      "1 cup corn kernels (fresh or frozen)",
      "1 can (15 oz) black beans, drained and rinsed",
      "1 can (14 oz) diced tomatoes",
      "1 tsp cumin",
      "1 tsp chili powder",
      "1/2 tsp paprika",
      "1/4 tsp cayenne pepper (optional)",
      "1/2 cup shredded cheese (cheddar or Mexican blend)",
      "Salt and pepper to taste",
      "Fresh cilantro, chopped, for garnish",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Cook quinoa in vegetable broth according to package instructions, then set aside.",
      "Heat olive oil in a large skillet over medium heat. Add onion and cook until softened, about 5 minutes.",
      "Add garlic and cook for 30 seconds until fragrant.",
      "Add zucchini and corn, cook for 3-4 minutes until vegetables begin to soften.",
      "Stir in black beans, diced tomatoes, cumin, chili powder, paprika, cayenne (if using), salt and pepper. Simmer for 5 minutes.",
      "Remove from heat and stir in cooked quinoa until well combined.",
      "Place bell peppers upright in a baking dish. Fill each pepper with the quinoa mixture.",
      "Cover the dish with foil and bake for 30 minutes. Remove foil, sprinkle with cheese, and bake uncovered for another 10 minutes until peppers are tender and cheese is melted.",
      "Garnish with fresh cilantro before serving.",
    ],
  },
  {
    title: "Sweet Potato and Black Bean Chili",
    image:
      "https://images.unsplash.com/photo-1633436375153-d7045cb93e38?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1025&q=80",
    tags: ["Vegan", "One Pot", "Comfort Food"],
    prepTime: "15 min",
    cookTime: "40 min",
    servings: "6",
    nutrition: {
      calories: "310 kcal",
      protein: "12g",
      carbs: "54g",
      fat: "6g",
    },
    ingredients: [
      "2 tbsp olive oil",
      "1 large onion, diced",
      "3 cloves garlic, minced",
      "2 sweet potatoes, peeled and diced into 1/2-inch cubes",
      "1 red bell pepper, diced",
      "2 tbsp chili powder",
      "1 tbsp ground cumin",
      "1 tsp smoked paprika",
      "1/4 tsp cinnamon",
      "2 cans (15 oz each) black beans, drained and rinsed",
      "1 can (28 oz) diced tomatoes",
      "2 cups vegetable broth",
      "1 cup corn kernels (fresh or frozen)",
      "1 tbsp lime juice",
      "Salt and pepper to taste",
      "Toppings: avocado slices, cilantro, lime wedges",
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Add onion and cook until softened, about 5 minutes.",
      "Add garlic and cook for 30 seconds until fragrant.",
      "Stir in sweet potatoes and bell pepper, cook for 5 minutes.",
      "Add chili powder, cumin, smoked paprika, and cinnamon. Stir to coat vegetables with spices.",
      "Add black beans, diced tomatoes, and vegetable broth. Bring to a boil, then reduce heat to low and simmer, covered, for 25-30 minutes until sweet potatoes are tender.",
      "Stir in corn and lime juice, cook for another 5 minutes.",
      "Season with salt and pepper to taste.",
      "Serve hot with avocado slices, cilantro, and lime wedges.",
    ],
  },
  {
    title: "Greek Yogurt Parfait",
    image:
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1087&q=80",
    tags: ["Breakfast", "Quick", "High Protein"],
    prepTime: "10 min",
    cookTime: "0 min",
    servings: "2",
    nutrition: {
      calories: "280 kcal",
      protein: "18g",
      carbs: "36g",
      fat: "8g",
    },
    ingredients: [
      "2 cups Greek yogurt",
      "2 tbsp honey or maple syrup",
      "1 tsp vanilla extract",
      "1 cup mixed berries (strawberries, blueberries, raspberries)",
      "1/2 cup granola",
      "2 tbsp chia seeds",
      "2 tbsp sliced almonds",
      "Fresh mint leaves for garnish (optional)",
    ],
    instructions: [
      "In a small bowl, mix Greek yogurt with honey or maple syrup and vanilla extract.",
      "In two serving glasses or bowls, layer the ingredients starting with a spoonful of yogurt mixture at the bottom.",
      "Add a layer of mixed berries, then a sprinkle of granola and chia seeds.",
      "Repeat the layers until all ingredients are used, finishing with berries and sliced almonds on top.",
      "Garnish with fresh mint leaves if desired.",
      "Serve immediately or refrigerate for up to 2 hours before serving.",
    ],
  },
]

export default recipes;

